networks:
  character-service:
    name: character-service
    driver: bridge
  eureka-network:
    external: true

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DB_PATH
  backend_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $BACKEND_PATH
services:

  postgres:
    container_name: postgres-character
    image: postgres:latest
    restart: always
    ports:
      - "8001:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - character-service

  backend-character-service:
    container_name: backend-character-service
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always
    networks:
      - character-service
      - eureka-network
    volumes:
      - backend_code:/app
    env_file:
      - .env