networks:
  node_service:
    name: character-service
    driver: bridge
  dungeon-space-network:
    external: true

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $DB_PATH
  backend_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $BACKEND_PATH

services:
  postgres:
    container_name: postgres-character
    image: postgres:latest
    restart: always
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - node_service

  backend-node-service:
    container_name: backend-character-service
    build:
      context: .
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    restart: always
    networks:
      - node_service
      - dungeon-space-network
    volumes:
      - backend_code:/app
    env_file:
      - .env