import { SRD_PROVENANCE, type SpellEntry } from './types';

type S = Omit<SpellEntry, 'kind' | 'provenance' | 'concentration' | 'ritual' | 'components'> &
  Partial<Pick<SpellEntry, 'concentration' | 'ritual' | 'components'>>;

const spell = (s: S): SpellEntry => ({
  kind: 'spell',
  concentration: false,
  ritual: false,
  components: ['V', 'S'],
  provenance: SRD_PROVENANCE,
  ...s,
});

/** Sorts du SRD 5.1 tels que résumés (sans leurs mécaniques de combat, ajoutées plus bas). */
const BASE: SpellEntry[] = [
  spell({ id: 'fire-bolt', name: 'Trait de feu', level: 0, school: 'Évocation', castingTime: '1 action', range: '36 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Un trait enflammé frappe une créature ou un objet à distance.', roll: '1d10', damageType: 'feu' }),
  spell({ id: 'sacred-flame', name: 'Flamme sacrée', level: 0, school: 'Évocation', castingTime: '1 action', range: '18 m', duration: 'Instantanée', classes: ['Clerc'], summary: 'Une lueur radiante descend sur la cible, qui doit réussir un JS de Dextérité.', roll: '1d8', damageType: 'radiant', save: 'dex' }),
  spell({ id: 'eldritch-blast', name: 'Décharge occulte', level: 0, school: 'Évocation', castingTime: '1 action', range: '36 m', duration: 'Instantanée', classes: ['Occultiste'], summary: "Un rayon d'énergie crépitante ; plusieurs rayons aux niveaux supérieurs.", roll: '1d10', damageType: 'force' }),
  spell({ id: 'ray-of-frost', name: 'Rayon de givre', level: 0, school: 'Évocation', castingTime: '1 action', range: '18 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Un rayon glacé qui inflige du froid et réduit la vitesse de la cible de 3 m.', roll: '1d8', damageType: 'froid' }),
  spell({ id: 'light', name: 'Lumière', level: 0, school: 'Évocation', castingTime: '1 action', range: 'Contact', duration: '1 heure', classes: ['Barde', 'Clerc', 'Ensorceleur', 'Magicien'], summary: 'Un objet émet une lumière vive dans un rayon de 6 m.', components: ['V', 'M'] }),
  spell({ id: 'mage-hand', name: 'Main de mage', level: 0, school: 'Invocation', castingTime: '1 action', range: '9 m', duration: '1 minute', classes: ['Barde', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Une main spectrale manipule de petits objets à distance.' }),
  spell({ id: 'magic-missile', name: 'Projectile magique', level: 1, school: 'Évocation', castingTime: '1 action', range: '36 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Trois fléchettes de force touchent automatiquement leurs cibles (1d4 + 1 chacune).', roll: '3d4+3', damageType: 'force' }),
  spell({ id: 'cure-wounds', name: 'Soins', level: 1, school: 'Évocation', castingTime: '1 action', range: 'Contact', duration: 'Instantanée', classes: ['Barde', 'Clerc', 'Druide', 'Paladin', 'Rôdeur'], summary: 'Une créature touchée récupère 1d8 + votre modificateur de sorts en PV. Sans effet sur les morts-vivants.', roll: '1d8' }),
  spell({ id: 'healing-word', name: 'Mot de guérison', level: 1, school: 'Évocation', castingTime: '1 action bonus', range: '18 m', duration: 'Instantanée', classes: ['Barde', 'Clerc', 'Druide'], summary: 'Une créature visible récupère 1d4 + votre modificateur de sorts en PV.', roll: '1d4', components: ['V'] }),
  spell({ id: 'shield', name: 'Bouclier', level: 1, school: 'Abjuration', castingTime: '1 réaction', range: 'Personnelle', duration: '1 round', classes: ['Ensorceleur', 'Magicien'], summary: "Une barrière invisible accorde +5 à la CA jusqu'au début de votre prochain tour." }),
  spell({ id: 'burning-hands', name: 'Mains brûlantes', level: 1, school: 'Évocation', castingTime: '1 action', range: 'Personnelle (cône 4,5 m)', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Un éventail de flammes jaillit de vos doigts ; JS de Dextérité pour moitié.', roll: '3d6', damageType: 'feu', save: 'dex', area: { shape: 'cone', size: 4.5 } }),
  spell({ id: 'thunderwave', name: 'Vague tonnante', level: 1, school: 'Évocation', castingTime: '1 action', range: 'Personnelle (cube 4,5 m)', duration: 'Instantanée', classes: ['Barde', 'Druide', 'Ensorceleur', 'Magicien'], summary: 'Une onde de choc repousse les créatures de 3 m ; JS de Constitution pour moitié.', roll: '2d8', damageType: 'tonnerre', save: 'con', area: { shape: 'cube', size: 4.5 } }),
  spell({ id: 'sleep', name: 'Sommeil', level: 1, school: 'Enchantement', castingTime: '1 action', range: '27 m', duration: '1 minute', classes: ['Barde', 'Ensorceleur', 'Magicien'], summary: 'Endort des créatures dont le total de PV (5d8) est le plus faible.', roll: '5d8', area: { shape: 'sphere', size: 6 } }),
  spell({ id: 'hunters-mark', name: 'Marque du chasseur', level: 1, school: 'Divination', castingTime: '1 action bonus', range: '27 m', duration: '1 heure', concentration: true, classes: ['Rôdeur'], summary: "La cible subit 1d6 dégâts supplémentaires à chaque attaque d'arme qui la touche.", roll: '1d6', components: ['V'] }),
  spell({ id: 'bless', name: 'Bénédiction', level: 1, school: 'Enchantement', castingTime: '1 action', range: '9 m', duration: '1 minute', concentration: true, classes: ['Clerc', 'Paladin'], summary: "Jusqu'à trois créatures ajoutent 1d4 à leurs jets d'attaque et de sauvegarde.", roll: '1d4' }),
  spell({ id: 'detect-magic', name: 'Détection de la magie', level: 1, school: 'Divination', castingTime: '1 action', range: 'Personnelle', duration: '10 minutes', concentration: true, ritual: true, classes: ['Barde', 'Clerc', 'Druide', 'Magicien', 'Paladin', 'Rôdeur', 'Ensorceleur'], summary: 'Vous percevez la présence de magie à 9 m autour de vous.' }),
  spell({ id: 'longstrider', name: 'Grande foulée', level: 1, school: 'Transmutation', castingTime: '1 action', range: 'Contact', duration: '1 heure', classes: ['Barde', 'Druide', 'Magicien', 'Rôdeur'], summary: 'La vitesse de la cible augmente de 3 m.' }),
  spell({ id: 'speak-with-animals', name: 'Communication avec les animaux', level: 1, school: 'Divination', castingTime: '1 action', range: 'Personnelle', duration: '10 minutes', ritual: true, classes: ['Barde', 'Druide', 'Rôdeur'], summary: 'Vous comprenez les bêtes et pouvez leur parler.' }),
  spell({ id: 'mage-armor', name: 'Armure de mage', level: 1, school: 'Abjuration', castingTime: '1 action', range: 'Contact', duration: '8 heures', classes: ['Ensorceleur', 'Magicien'], summary: 'Une créature sans armure a une CA de base de 13 + DEX.' }),
  spell({ id: 'charm-person', name: 'Charme-personne', level: 1, school: 'Enchantement', castingTime: '1 action', range: '9 m', duration: '1 heure', classes: ['Barde', 'Druide', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: "Un humanoïde vous considère comme une connaissance amicale (JS de Sagesse).", save: 'wis' }),
  spell({ id: 'web', name: "Toile d'araignée", level: 2, school: 'Invocation', castingTime: '1 action', range: '18 m', duration: '1 heure', concentration: true, classes: ['Ensorceleur', 'Magicien'], summary: "Des fils collants remplissent un cube de 6 m et entravent les créatures (JS de Dextérité).", save: 'dex', area: { shape: 'cube', size: 6 } }),
  spell({ id: 'pass-without-trace', name: 'Passage sans trace', level: 2, school: 'Abjuration', castingTime: '1 action', range: 'Personnelle', duration: '1 heure', concentration: true, classes: ['Druide', 'Rôdeur'], summary: 'Vous et vos alliés à 9 m gagnez +10 aux tests de Discrétion.' }),
  spell({ id: 'barkskin', name: "Peau d'écorce", level: 2, school: 'Transmutation', castingTime: '1 action', range: 'Contact', duration: '1 heure', concentration: true, classes: ['Druide', 'Rôdeur'], summary: 'La CA de la cible ne peut pas être inférieure à 16.' }),
  spell({ id: 'spiritual-weapon', name: 'Arme spirituelle', level: 2, school: 'Évocation', castingTime: '1 action bonus', range: '18 m', duration: '1 minute', classes: ['Clerc'], summary: 'Une arme spectrale flottante attaque au corps à corps.', roll: '1d8', damageType: 'force' }),
  spell({ id: 'scorching-ray', name: 'Rayon ardent', level: 2, school: 'Évocation', castingTime: '1 action', range: '36 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Trois rayons de feu ; chacun inflige 2d6 dégâts sur un coup au but.', roll: '2d6', damageType: 'feu' }),
  spell({ id: 'hold-person', name: 'Immobilisation de personne', level: 2, school: 'Enchantement', castingTime: '1 action', range: '18 m', duration: '1 minute', concentration: true, classes: ['Barde', 'Clerc', 'Druide', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Un humanoïde est paralysé (JS de Sagesse à chaque tour).', save: 'wis' }),
  spell({ id: 'invisibility', name: 'Invisibilité', level: 2, school: 'Illusion', castingTime: '1 action', range: 'Contact', duration: '1 heure', concentration: true, classes: ['Barde', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: "La cible devient invisible jusqu'à ce qu'elle attaque ou lance un sort." }),
  spell({ id: 'shatter', name: 'Fracassement', level: 2, school: 'Évocation', castingTime: '1 action', range: '18 m', duration: 'Instantanée', classes: ['Barde', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Un bruit assourdissant dans une sphère de 3 m ; JS de Constitution pour moitié.', roll: '3d8', damageType: 'tonnerre', save: 'con', area: { shape: 'sphere', size: 3 } }),
  spell({ id: 'cloud-of-daggers', name: 'Nuée de dagues', level: 2, school: 'Invocation', castingTime: '1 action', range: '18 m', duration: '1 minute', concentration: true, classes: ['Barde', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Un cube de 1,5 m de lames tournoyantes inflige 4d4 tranchants.', roll: '4d4', damageType: 'tranchant', area: { shape: 'cube', size: 1.5 } }),
  spell({ id: 'fireball', name: 'Boule de feu', level: 3, school: 'Évocation', castingTime: '1 action', range: '45 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Une perle incandescente éclate en une sphère de flammes de 6 m de rayon ; JS de Dextérité pour moitié.', roll: '8d6', damageType: 'feu', save: 'dex', area: { shape: 'sphere', size: 6 }, components: ['V', 'S', 'M'] }),
  spell({ id: 'lightning-bolt', name: 'Éclair', level: 3, school: 'Évocation', castingTime: '1 action', range: 'Personnelle (ligne 30 m)', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Une ligne de foudre de 30 m ; JS de Dextérité pour moitié.', roll: '8d6', damageType: 'foudre', save: 'dex', area: { shape: 'line', size: 30 } }),
  spell({ id: 'counterspell', name: 'Contresort', level: 3, school: 'Abjuration', castingTime: '1 réaction', range: '18 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Vous interrompez une créature en train de lancer un sort.', components: ['S'] }),
  spell({ id: 'dispel-magic', name: 'Dissipation de la magie', level: 3, school: 'Abjuration', castingTime: '1 action', range: '36 m', duration: 'Instantanée', classes: ['Barde', 'Clerc', 'Druide', 'Ensorceleur', 'Magicien', 'Occultiste', 'Paladin'], summary: "Met fin aux sorts de niveau 3 ou moins sur une cible." }),
  spell({ id: 'haste', name: 'Rapidité', level: 3, school: 'Transmutation', castingTime: '1 action', range: '9 m', duration: '1 minute', concentration: true, classes: ['Ensorceleur', 'Magicien'], summary: 'Vitesse doublée, +2 à la CA, avantage aux JS de DEX et une action supplémentaire.' }),
  spell({ id: 'revivify', name: 'Revigorer', level: 3, school: 'Nécromancie', castingTime: '1 action', range: 'Contact', duration: 'Instantanée', classes: ['Clerc', 'Paladin'], summary: 'Ramène à 1 PV une créature morte depuis moins d’une minute.' }),
  spell({ id: 'spirit-guardians', name: 'Esprits gardiens', level: 3, school: 'Invocation', castingTime: '1 action', range: 'Personnelle (4,5 m)', duration: '10 minutes', concentration: true, classes: ['Clerc'], summary: 'Des esprits ralentissent et blessent les ennemis autour de vous (JS de Sagesse).', roll: '3d8', damageType: 'radiant', save: 'wis', area: { shape: 'sphere', size: 4.5 } }),
  spell({ id: 'fly', name: 'Vol', level: 3, school: 'Transmutation', castingTime: '1 action', range: 'Contact', duration: '10 minutes', concentration: true, classes: ['Ensorceleur', 'Magicien', 'Occultiste'], summary: 'La cible gagne une vitesse de vol de 18 m.' }),
  spell({ id: 'dimension-door', name: 'Porte dimensionnelle', level: 4, school: 'Invocation', castingTime: '1 action', range: '150 m', duration: 'Instantanée', classes: ['Barde', 'Ensorceleur', 'Magicien', 'Occultiste'], summary: 'Vous vous téléportez, éventuellement avec un allié.', components: ['V'] }),
  spell({ id: 'wall-of-fire', name: 'Mur de feu', level: 4, school: 'Évocation', castingTime: '1 action', range: '36 m', duration: '1 minute', concentration: true, classes: ['Druide', 'Ensorceleur', 'Magicien'], summary: 'Un mur de flammes inflige 5d8 dégâts à qui le traverse.', roll: '5d8', damageType: 'feu', save: 'dex' }),
  spell({ id: 'banishment', name: 'Bannissement', level: 4, school: 'Abjuration', castingTime: '1 action', range: '18 m', duration: '1 minute', concentration: true, classes: ['Clerc', 'Ensorceleur', 'Magicien', 'Occultiste', 'Paladin'], summary: 'Expulse une créature vers un demi-plan (JS de Charisme).', save: 'cha' }),
  spell({ id: 'cone-of-cold', name: 'Cône de froid', level: 5, school: 'Évocation', castingTime: '1 action', range: 'Personnelle (cône 18 m)', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Un souffle glacial ; JS de Constitution pour moitié.', roll: '8d8', damageType: 'froid', save: 'con', area: { shape: 'cone', size: 18 } }),
  spell({ id: 'raise-dead', name: 'Rappel à la vie', level: 5, school: 'Nécromancie', castingTime: '1 heure', range: 'Contact', duration: 'Instantanée', classes: ['Barde', 'Clerc', 'Paladin'], summary: 'Ramène à la vie une créature morte depuis moins de 10 jours.' }),
  spell({ id: 'disintegrate', name: 'Désintégration', level: 6, school: 'Transmutation', castingTime: '1 action', range: '18 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Un rayon vert réduit la cible en poussière (JS de Dextérité).', roll: '10d6+40', damageType: 'force', save: 'dex' }),
  spell({ id: 'finger-of-death', name: 'Doigt de mort', level: 7, school: 'Nécromancie', castingTime: '1 action', range: '18 m', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien', 'Occultiste'], summary: "Une énergie négative dévastatrice ; JS de Constitution pour moitié.", roll: '7d8+30', damageType: 'nécrotique', save: 'con' }),
  spell({ id: 'wish', name: 'Souhait', level: 9, school: 'Invocation', castingTime: '1 action', range: 'Personnelle', duration: 'Instantanée', classes: ['Ensorceleur', 'Magicien'], summary: 'Le sort le plus puissant qui soit : reproduit un autre sort ou altère la réalité.', components: ['V'] }),
];

/** Mécaniques de résolution en combat (attaque, sauvegarde, état, montée en puissance). */
const MECHANICS: Record<string, Partial<SpellEntry>> = {
  'fire-bolt': { attack: true },
  'eldritch-blast': { attack: true },
  'ray-of-frost': { attack: true },
  'scorching-ray': { attack: true, targets: 3 },
  'spiritual-weapon': { attack: true },
  'sacred-flame': { half: false },
  'magic-missile': { upcast: '1d4+1' },
  'cure-wounds': { heal: true, upcast: '1d8' },
  'healing-word': { heal: true, upcast: '1d4' },
  'burning-hands': { half: true, upcast: '1d6' },
  thunderwave: { half: true, upcast: '1d8' },
  sleep: { condition: 'Inconscient', upcast: '2d8' },
  'hunters-mark': { condition: 'Marqué' },
  bless: { condition: 'Béni', targets: 3 },
  'charm-person': { condition: 'Charmé' },
  web: { condition: 'Entravé' },
  barkskin: { condition: "Peau d'écorce" },
  'hold-person': { condition: 'Paralysé' },
  invisibility: { condition: 'Invisible' },
  shatter: { half: true, upcast: '1d8' },
  'cloud-of-daggers': { upcast: '2d4' },
  fireball: { half: true, upcast: '1d6' },
  'lightning-bolt': { half: true, upcast: '1d6' },
  'spirit-guardians': { half: true, upcast: '1d8' },
  'wall-of-fire': { half: true, upcast: '1d8' },
  banishment: { condition: 'Neutralisé' },
  'cone-of-cold': { half: true, upcast: '1d8' },
  disintegrate: { half: false, upcast: '3d6' },
  'finger-of-death': { half: true },
};

/** Sélection de sorts du SRD 5.1 — mécaniques du SRD, résumés rédigés pour DungeonSpace. */
export const SPELLS: SpellEntry[] = BASE.map((s) => ({ ...s, ...MECHANICS[s.id] }));
